<script setup lang="ts">
import { useId } from 'vue';
import { reportObservationText, type ReportDocument } from '#shared/mission-report';
import { assessmentLabels } from '#shared/result-assessment';
import { qualityLabels } from '#shared/quality';
import { safeReportUrl } from '#shared/report-sharing';
import type { DiagramContent } from '#shared/diagram';
const props = defineProps<{ document: ReportDocument; assets?: { id: string; url: string }[]; canOpenEvidence?: boolean }>();
defineEmits<{ openEvidence: [itemId: string] }>();
const reportInstanceId = useId();
const evidenceAnchor = (id: string) => `${reportInstanceId}-evidence-${id.replace(/[^\w-]/g, '-')}`;
const statuses: Record<string, string> = { planned: 'Planerat', pending: 'Planerat', ready: 'Redo', waiting: 'Väntar', running: 'Pågår', completed: 'Avslutat', blocked: 'Blockerat', failed: 'Misslyckat', cancelled: 'Avbrutet', unknown: 'Okänt' };
const actors: Record<string, string> = { main: 'V', browser: 'Iris', repo: 'Axel', vps: 'Otto' };
const goals: Record<string, string> = { achieved: 'Uppnått', partial: 'Delvis uppnått', blocked: 'Blockerat', unknown: 'Okänt' };
const outcome = (s: string) => qualityLabels[s as keyof typeof qualityLabels] ?? s;
const verdict = (s: string) => assessmentLabels[s as keyof typeof assessmentLabels] ?? ({ unreviewed: 'Ej granskat', queued: 'Köad', running: 'Granskas', failed: 'Granskning misslyckades' }[s] ?? s);
const taskDiagram = computed<DiagramContent>(() => {
  const tasks = props.document.tasks.slice(0, 150), ids = new Set(tasks.map(t => t.id));
  return { kind: 'diagram', direction: 'LR', summary: '', sources: [], nodes: tasks.map(t => ({ id: t.id, label: t.title.slice(0, 160), category: actors[t.actor] ?? t.actor, url: '', description: `${statuses[t.status]} · Start ${t.startedAt ?? 'okänd'} · Slut ${t.finishedAt ?? 'ej registrerat'}` })), edges: tasks.flatMap(t => [...(t.parentId ? [{ source: t.parentId, label: 'Deluppgift' }] : []), ...t.dependsOn.map(source => ({ source, label: 'Beroende' }))].filter(e => ids.has(e.source)).map((e, i) => ({ ...e, id: `${t.id}-${i}`, target: t.id, status: 'verified' as const, evidence: `Registrerat i uppdragets revision ${props.document.revision}. Sambandet beskriver arbetsplanen, inte ett verifierat produktbeteende.` }))).slice(0, 400) };
});
</script>
<template>
  <article class="report-document space-y-6 text-sm">
    <header class="space-y-2"><p class="text-xs text-muted">Klara · {{ document.partial ? 'Delrapport' : 'Slutrapport' }} · revision {{ document.revision }}</p><h1 class="text-2xl font-semibold">{{ document.title }}</h1><p class="text-muted">{{ new Date(document.capturedAt).toLocaleString('sv-SE') }} · {{ document.target }}</p><p class="whitespace-pre-wrap leading-relaxed">{{ document.summary }}</p></header>
    <section class="space-y-2"><h2 class="text-lg font-semibold">Mål och omfattning</h2><p class="whitespace-pre-wrap">{{ document.goal }}</p><p class="whitespace-pre-wrap text-muted">{{ document.scope }}</p></section>
    <p v-if="document.metrics.length" class="text-xs text-muted">Graferna visar rapporterade testutfall. Klaras granskning visas separat och kan begära komplettering.</p>
    <section v-if="document.metrics.length" class="grid gap-4 @xl:grid-cols-2"><div v-for="metric in document.metrics" :key="metric.id" class="rounded-lg border border-default p-3"><WorkspaceChart :chart="{ kind: 'chart', chartType: 'bar', title: metric.label, data: metric.data }" /><details class="mt-2"><summary>Visa siffror</summary><dl><div v-for="point in metric.data" :key="point.label" class="flex justify-between gap-4"><dt>{{ point.label }}</dt><dd>{{ point.value }}</dd></div></dl></details></div></section>
    <section class="space-y-3"><h2 class="text-lg font-semibold">Bedömning och nästa steg</h2><div v-for="finding in document.findings" :key="finding.criterionId" class="rounded-lg border border-default p-3"><p class="mb-2 font-medium">{{ document.criteria?.find(c => c.id === finding.criterionId)?.text }}</p><UBadge :label="verdict(finding.verdict)" :color="finding.verdict === 'supported' ? 'success' : 'warning'" variant="subtle" /><div v-if="finding.observations?.length" class="mt-3 space-y-2"><h3 class="font-medium">Klaras observationer</h3><div v-for="(observation, index) in finding.observations" :key="index"><p class="text-xs text-muted">{{ observation.originLabel }}</p><p class="whitespace-pre-wrap">{{ reportObservationText(observation) }}</p><div class="mt-1 flex flex-wrap gap-2"><a v-for="id in observation.evidenceIds" :key="id" :href="`#${evidenceAnchor(id)}`" class="text-xs underline">{{ document.evidence.find(e => e.id === id)?.title ?? 'Underlag' }}</a></div></div></div><p class="mt-2 whitespace-pre-wrap"><strong v-if="finding.completionStatement">Kriteriets status: </strong>{{ finding.completionStatement ?? finding.conclusion }}</p><p v-if="finding.nextStep" class="mt-2"><strong>Nästa steg:</strong> {{ finding.nextStep }}</p><div class="mt-2 flex flex-wrap gap-2"><a v-for="id in finding.evidenceIds" :key="id" :href="`#${evidenceAnchor(id)}`" class="text-xs underline">{{ document.evidence.find(e => e.id === id)?.title ?? 'Underlag' }}</a></div></div></section>
    <section v-if="document.tests.length" class="space-y-2"><h2 class="text-lg font-semibold">Testresultat</h2><div class="overflow-auto"><table class="w-full text-left"><thead><tr><th>Testfall och testobjekt</th><th>Utfall</th><th>Granskning</th></tr></thead><tbody><tr v-for="test in document.tests" :key="test.key"><td>{{ test.title }}<p class="text-xs text-muted">{{ test.target }}</p></td><td>{{ outcome(test.status) }}<p v-if="test.manualReview" class="mt-1 text-xs">Manuell bedömning: {{ test.manualReview }}<br>Ursprungligt utfall: {{ outcome(test.originalOutcome ?? 'untested') }}</p></td><td>{{ verdict(test.review) }}</td></tr></tbody></table></div></section>
    <section v-if="document.tasks.length" class="space-y-2 print:hidden"><h2 class="text-lg font-semibold">Uppgiftskarta</h2><ClientOnly><WorkspaceDiagram :diagram="taskDiagram" /></ClientOnly><p v-if="document.tasks.length > 150" class="text-xs text-muted">Kartan visar de första 150 uppgifterna. Alla finns i listan nedan.</p></section>
    <section class="space-y-2"><h2 class="text-lg font-semibold">Arbete och beroenden</h2><ol class="space-y-2"><li v-for="task in document.tasks" :key="task.id" class="rounded-lg border border-default p-3"><p class="font-medium">{{ actors[task.actor] ?? task.actor }} · {{ task.title }}</p><p class="text-muted">{{ statuses[task.status] ?? task.status }}<span v-if="task.startedAt"> · {{ new Date(task.startedAt).toLocaleString('sv-SE') }}</span><span v-if="task.finishedAt"> → {{ new Date(task.finishedAt).toLocaleString('sv-SE') }}</span></p><p class="text-xs">Rapporterat målutfall: {{ goals[task.reportedOutcome] ?? 'Okänt' }}</p><p v-if="task.parentId" class="text-xs">Del av: {{ document.tasks.find(t => t.id === task.parentId)?.title }}</p><p v-if="task.dependsOn.length" class="text-xs">Beror på: {{ task.dependsOn.map(id => document.tasks.find(t => t.id === id)?.title ?? 'Okänd uppgift').join(', ') }}</p></li></ol></section>
    <section v-if="document.limitations.length" class="space-y-2"><h2 class="text-lg font-semibold">Begränsningar och luckor</h2><ul class="list-disc space-y-1 pl-5"><li v-for="(gap, index) in document.limitations" :key="index">{{ gap }}</li></ul></section>
    <section class="space-y-3"><h2 class="text-lg font-semibold">Underlag</h2><div v-for="ref in document.evidence" :id="evidenceAnchor(ref.id)" :key="ref.id" class="rounded-lg border border-default p-3"><p class="font-medium">{{ ref.title }}</p><p class="text-xs text-muted">{{ ref.read ? 'Läst i granskningen' : 'Inte läst i denna granskning' }}<span v-if="ref.observedAt"> · {{ new Date(ref.observedAt).toLocaleString('sv-SE') }}</span></p><UButton v-if="canOpenEvidence && ref.itemId" label="Öppna underlag i Material" icon="i-lucide-paperclip" size="sm" variant="link" color="neutral" class="print:hidden" @click="$emit('openEvidence', ref.itemId)" /><a v-if="safeReportUrl(ref.url)" :href="safeReportUrl(ref.url)!" target="_blank" rel="noopener noreferrer" class="break-all underline">{{ safeReportUrl(ref.url) }}</a><img v-if="props.assets?.find(a => a.id === ref.id)" :src="props.assets.find(a => a.id === ref.id)!.url" :alt="ref.title" loading="lazy" class="mt-3 max-h-[32rem] max-w-full object-contain"><p v-else-if="ref.kind === 'unshared'" class="text-xs text-muted">Bilagan ingår inte i delningen.</p></div></section>
  </article>
</template>
<style scoped>
.report-document { min-width: 0; overflow-wrap: anywhere; }
th, td { padding: .65rem; border-bottom: 1px solid var(--ui-border); vertical-align: top; }
@media print { header, li, tr, h2 { break-inside: avoid; } h2 { break-after: avoid; } details > * { display: block; } }
</style>
