<script setup lang="ts">
import type { ReportDocument } from '#shared/mission-report';
const props = defineProps<{ workspaceId: string; reportId: string; document: ReportDocument }>();
const open = ref(false), selected = ref(''), previous = ref<ReportDocument | null>(null), busy = ref(false), error = ref('');
const { data } = useMissions();
const options = computed(() => data.value?.missions.flatMap(m => m.reports.filter(r => r.id !== props.reportId && r.itemId && !r.deleted).map(r => ({ value: r.id, label: `${m.config.title} · revision ${r.revision}` }))) ?? []);
watch(selected, async id => { previous.value = null; if (!id) return; busy.value = true; error.value = ''; try { const result = await $fetch<{ document: ReportDocument | null }>(`/api/workspaces/${props.workspaceId}/reports/${id}`); if (selected.value === id) previous.value = result.document; } catch { error.value = 'Den valda rapporten kunde inte hämtas.'; } finally { busy.value = false; } });
</script>
<template>
  <UModal v-model:open="open" title="Jämför rapporter" description="Varje rapport behåller sitt testurval, testobjekt och sina begränsningar." :ui="{ content: 'max-w-5xl' }">
    <UButton label="Jämför" icon="i-lucide-columns-2" color="neutral" variant="ghost" />
    <template #body><div class="space-y-4"><UFormField label="Jämför med"><USelect v-model="selected" :items="options" placeholder="Välj sparad rapport" class="w-full" /></UFormField><p v-if="busy" role="status">Hämtar rapport…</p><p v-if="error" role="alert">{{ error }}</p><p v-if="!options.length" class="text-muted">Spara en till rapport för att jämföra.</p><template v-if="previous"><p class="rounded-lg bg-elevated p-3 text-sm">{{ document.target === previous.target && document.scope === previous.scope ? 'Kontrollera även testurval och definitioner innan du tolkar skillnader som en förbättring eller regression.' : 'Rapporterna har olika testobjekt eller omfattning. Antalen ska inte jämföras som ett direkt kvalitetsmått.' }}</p><div class="grid gap-5 md:grid-cols-2"><section v-for="(report, i) in [previous, document]" :key="i" class="min-w-0 space-y-3"><h3 class="font-semibold">{{ report.title }} · revision {{ report.revision }}</h3><p class="break-words text-sm">{{ report.target }}</p><p class="text-xs text-muted">{{ report.capturedAt }}<br>{{ report.scope }}</p><p class="text-sm">{{ report.summary }}</p><div v-for="metric in report.metrics" :key="metric.id"><h4 class="text-sm font-medium">{{ metric.label }}</h4><dl class="text-sm"><div v-for="point in metric.data" :key="point.label" class="flex justify-between"><dt>{{ point.label }}</dt><dd>{{ point.value }}</dd></div></dl></div><p class="text-sm">{{ report.findings.filter(f => f.verdict === 'supported').length }} av {{ report.findings.length }} kriteriebedömningar underbyggda. Underbyggt betyder inte att målet uppnåddes.</p><ul class="list-disc pl-5 text-xs text-muted"><li v-for="limit in report.limitations" :key="limit">{{ limit }}</li></ul></section></div></template></div></template>
  </UModal>
</template>
