import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm, access } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import test from 'node:test';
import { authoredFingerprint, withArtifactLocks } from './helpers/isolated-build-integrity.mjs';
import { withEvidencePreparationFence } from './helpers/evidence-preparation-fence.mjs';

async function fixture(t) {
  const repositoryRoot = await mkdtemp(resolve(tmpdir(), 'syna-preparation-fence-'));
  t.after(() => rm(repositoryRoot, { recursive: true, force: true }));
  const appRoot = resolve(repositoryRoot, '.data/autonomy-isolation/application-a123'), files = ['server/example.ts'];
  await mkdir(resolve(repositoryRoot, 'server'), { recursive: true }); await mkdir(resolve(appRoot, 'web/server'), { recursive: true });
  for (const root of [repositoryRoot, resolve(appRoot, 'web')]) await writeFile(resolve(root, files[0]), 'export const prepared = true;');
  const expectedSource = await authoredFingerprint(repositoryRoot, files);
  await writeFile(resolve(appRoot, 'source-manifest.json'), JSON.stringify({ sourceSha256: expectedSource, files }));
  const observed = { stopped: 0, idle: 0 };
  return { repositoryRoot, appRoot, expectedSource, observed,
    verifyStopped: async () => { observed.stopped++; }, verifyIdle: async () => ({ checks: ++observed.idle, noForeignWork: true }) };
}

test('preparation holds every real artifact lock through the action and keeps idle checks outside its own writes', async t => {
  const f = await fixture(t); let writes = 0;
  const { receipt } = await withEvidencePreparationFence(f, async ({ assertExclusive, identity }) => {
    assert.equal(identity.sourceSha256, f.expectedSource); writes++;
    await assert.rejects(withArtifactLocks(f.appRoot, ['web'], async () => assert.fail('start must not enter')), /busy/);
    await assert.rejects(withArtifactLocks(f.appRoot, ['dependencies', 'eve'], async () => assert.fail('build must not enter')), /busy/);
    await assertExclusive(); assert.equal(f.observed.idle, 1, 'No global idle requirement during owned writes');
  });
  assert.equal(writes, 1); assert.equal(f.observed.idle, 2); assert.ok(receipt.completedAt);
  for (const key of ['web', 'eve', 'dependencies']) await assert.rejects(access(resolve(f.appRoot, `artifact-${key}.lock`)));
});

test('changed working code, snapshot, declared identity or existing operation denies before writes', async t => {
  for (const kind of ['working', 'snapshot', 'identity', 'lock', 'running', 'foreign-work']) {
    const f = await fixture(t); let writes = 0;
    if (kind === 'working') await writeFile(resolve(f.repositoryRoot, 'server/example.ts'), 'changed');
    if (kind === 'snapshot') await writeFile(resolve(f.appRoot, 'web/server/example.ts'), 'changed');
    if (kind === 'identity') f.expectedSource = 'a'.repeat(64);
    if (kind === 'lock') await writeFile(resolve(f.appRoot, 'artifact-eve.lock'), 'other operation');
    if (kind === 'running') f.verifyStopped = async () => { throw new Error('Running'); };
    if (kind === 'foreign-work') f.verifyIdle = async () => { throw new Error('Foreign work'); };
    await assert.rejects(withEvidencePreparationFence(f, async () => { writes++; })); assert.equal(writes, 0);
    if (kind === 'lock') assert.equal(await readFile(resolve(f.appRoot, 'artifact-eve.lock'), 'utf8'), 'other operation');
  }
});

test('source mutation during preparation or unclean exit cannot yield a completed fence receipt', async t => {
  const f = await fixture(t);
  await assert.rejects(withEvidencePreparationFence(f, async () => {
    await writeFile(resolve(f.repositoryRoot, 'server/example.ts'), 'changed after writes');
  }), /differs from the frozen source/);
  const other = await fixture(t);
  await assert.rejects(withEvidencePreparationFence(other, async () => { throw new Error('unknown preparation outcome'); }), /unknown preparation outcome/);
  await withArtifactLocks(other.appRoot, ['web', 'eve', 'dependencies'], async () => {});
});

test('real manifest scaffolds stay frozen while every non-generated authored file and schema inventory must match', async t => {
  const f = await fixture(t), generated = ['.cssnanorc.json', 'tests/helpers/observe-http.mjs', 'tests/helpers/isolation-module-fence.mjs'];
  await mkdir(resolve(f.appRoot, 'web/tests/helpers'), { recursive: true });
  for (const file of generated) await writeFile(resolve(f.appRoot, 'web', file), 'frozen generated bytes');
  const files = ['server/example.ts', ...generated];
  f.expectedSource = await authoredFingerprint(resolve(f.appRoot, 'web'), files);
  await writeFile(resolve(f.appRoot, 'source-manifest.json'), JSON.stringify({ sourceSha256: f.expectedSource, files }));
  const result = await withEvidencePreparationFence(f, async () => 'prepared'); assert.equal(result.result, 'prepared');
  assert.notEqual(result.receipt.authoredSha256, f.expectedSource);
  await mkdir(resolve(f.repositoryRoot, 'server/db/schema'), { recursive: true });
  await writeFile(resolve(f.repositoryRoot, 'server/db/schema/extra.ts'), 'new schema not in snapshot');
  await assert.rejects(withEvidencePreparationFence(f, async () => assert.fail('unfrozen schema')), /schema inventory/);
  await rm(resolve(f.repositoryRoot, 'server/db/schema/extra.ts'));
  await writeFile(resolve(f.appRoot, 'web', generated[0]), 'changed scaffold');
  await assert.rejects(withEvidencePreparationFence(f, async () => assert.fail('changed scaffold')), /Frozen web source changed/);
});

test('manifest publication happens only after all final guards and before artifact lock release', async t => {
  for (const dirty of [false, true]) {
    const f = await fixture(t); let published = 0;
    const pending = withEvidencePreparationFence(f, async () => {
      if (dirty) await writeFile(resolve(f.repositoryRoot, 'server/example.ts'), 'changed');
      return { prepared: true };
    }, async (value, receipt) => {
      published++; assert.equal(f.observed.idle, 2); assert.ok(receipt.completedAt);
      await assert.rejects(withArtifactLocks(f.appRoot, ['web'], async () => assert.fail('publication lost lock')), /busy/);
      return value;
    });
    if (dirty) await assert.rejects(pending); else assert.deepEqual((await pending).result, { prepared: true });
    assert.equal(published, dirty ? 0 : 1);
  }
});
