// Requires a disposable fixture created with KEEP_MISSION_FIXTURE=1.
import { chromium } from 'playwright-core';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
if (process.env.RUN_MISSION_REPORT_UI !== '1') throw new Error('Set RUN_MISSION_REPORT_UI=1 to use the disposable fixture.');
const fixture=JSON.parse(await readFile('.data/mission-fixture.json','utf8'));
const origin='http://localhost:3000';
const browser=await chromium.launch({channel:'chrome',headless:true});
await mkdir('.data/mission-ui',{recursive:true});
const errors=[];
try {
 const owner=await browser.newContext({viewport:{width:1440,height:1000}});
 await owner.addCookies(fixture.cookie.split('; ').map(pair=>{const at=pair.indexOf('=');return {name:pair.slice(0,at),value:pair.slice(at+1),url:origin};}));
 const page=await owner.newPage(); page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`${origin}/chat/${fixture.threadId}?workspace=${fixture.workspaceId}`,{waitUntil:'networkidle'});
 console.log('Owner page',new URL(page.url()).pathname);
 await page.getByText('Blandat uppdrag · verifieringsrapport',{exact:true}).first().locator('..').getByRole('button',{name:'Öppna rapport',exact:true}).click();
 await page.getByRole('button',{name:'Dela rapport',exact:true}).waitFor();
 await page.screenshot({path:'.data/mission-ui/material-wide.png'});
 await page.getByRole('button',{name:'Dela rapport',exact:true}).click();
 await page.getByRole('heading',{name:'Dela rapport',exact:true}).waitFor();
 await page.screenshot({path:'.data/mission-ui/share-modal.png'});
 await page.keyboard.press('Escape');
 await page.goto(`${origin}/reports/${fixture.reportId}?workspace=${fixture.workspaceId}`,{waitUntil:'networkidle'});
 assert.equal(await page.locator('article h1').innerText(),'Blandat uppdrag · verifieringsrapport');
 await page.screenshot({path:'.data/mission-ui/report-wide.png',fullPage:true});
 await page.pdf({path:'.data/mission-ui/report.pdf',format:'A4',printBackground:true});
 await page.setViewportSize({width:390,height:844}); await page.emulateMedia({colorScheme:'dark'});
 await page.evaluate(()=>{localStorage.setItem('nuxt-color-mode','dark');}); await page.reload({waitUntil:'networkidle'});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'No page-level horizontal overflow');
 await page.screenshot({path:'.data/mission-ui/report-mobile-dark.png',fullPage:true});
 const path=`${origin}/api/workspaces/${fixture.workspaceId}/reports/${fixture.reportId}/share`;
 const created=await owner.request.post(path,{data:{action:'create',mode:'pin',pin:'382951',evidenceIds:[],expiresAt:null}}); assert.ok(created.ok());
 const share=(await created.json()).share;
 const anon=await browser.newContext({viewport:{width:390,height:844}});
 const recipient=await anon.newPage(); recipient.on('pageerror',e=>errors.push(e.message));
 const external=[]; recipient.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('data:')) external.push(new URL(r.url()).hostname);});
 await recipient.goto(origin+share.path,{waitUntil:'networkidle'});
 await recipient.getByRole('heading',{name:'Privat rapport',exact:true}).waitFor();
 assert.equal(await recipient.locator('article').count(),0);
 await recipient.getByLabel('Pinkod',{exact:true}).fill('111111'); await recipient.getByRole('button',{name:'Öppna rapport',exact:true}).click();
 await recipient.getByRole('alert').waitFor();
 await recipient.screenshot({path:'.data/mission-ui/pin-mobile.png'});
 await recipient.getByLabel('Pinkod',{exact:true}).fill('382951'); await recipient.getByLabel('Pinkod',{exact:true}).press('Enter');
 await recipient.locator('article h1').waitFor(); assert.equal(await recipient.locator('article h1').innerText(),'Blandat uppdrag · verifieringsrapport');
 await recipient.reload({waitUntil:'networkidle'}); await recipient.locator('article h1').waitFor();
 assert.equal(external.length,0,'Shared page must not send third-party requests');
 await owner.request.post(path,{data:{action:'revoke'}}); await recipient.reload({waitUntil:'networkidle'});
 await recipient.getByRole('heading',{name:'Länken är inte tillgänglig',exact:true}).waitFor();
 assert.equal(await recipient.locator('article').count(),0);
 assert.deepEqual(errors,[]);
 console.log('PASS Material report + share modal, light/wide and dark/mobile, PDF, clean anonymous PIN UI, keyboard submit, reload, revocation and no external requests');
}finally {await browser.close();}
