import { defineTool } from 'eve/tools';
import { z } from 'zod';
import { repositoryActionSchema } from '../../shared/repository';
import { repositoryRequestId } from '../../shared/repository-request.mjs';
import { appOrigin, internalHeaders } from '../lib/internal-api';
export default defineTool({
  description: 'Connect a public GitHub repository URL, inspect npm scripts, start an isolated VPS test run, list saved status/logs/results or cancel. Submission IDs are generated by the tool. If a start response is uncertain, list runs before starting again. Only administrator-approved repositories execute. Exit code 0 means the selected command succeeded, not that all test cases passed. Runs continue on the service; progress is under Testing. Do not repeatedly poll.',
  inputSchema: z.discriminatedUnion('action', [
    repositoryActionSchema.options[0],
    repositoryActionSchema.options[1],
    repositoryActionSchema.options[2].omit({ requestId: true }),
    repositoryActionSchema.options[3],
  ]),
  async execute(input, ctx) {
    const auth = ctx.session.auth.current;
    const threadId = auth?.attributes.browserThreadId;
    if (auth?.authenticator !== 'app' || !auth.principalId || typeof threadId !== 'string') return { error: 'Repository testing requires a workspace web chat.' };
    const action = input.action === 'start' ? { ...input, requestId: repositoryRequestId(threadId, ctx.callId) } : input;
    const response = await fetch(`${appOrigin()}/api/internal/repository`, { method: 'POST', headers: internalHeaders(), body: JSON.stringify({ userId: auth.principalId, threadId, input: action }), signal: ctx.abortSignal });
    if (!response.ok) return { error: 'Repository action failed. Open Repository testing under Testing for details. Do not repeatedly retry.' };
    return response.json();
  },
});
