import { defineTool } from 'eve/tools';
import { z } from 'zod';
import { repositoryActionSchema, repositorySchema } from '../../shared/repository';
import { repositoryRequestId } from '../../shared/repository-request.mjs';
import { repositoryContext } from '../../shared/repository-context.mjs';
import { appOrigin, internalHeaders } from '../lib/internal-api';
export default defineTool({
  description: 'Direct repository API, not a specialist: status requires {action:"list"}, never message/outputSchema. connect requires url (optional ref/script); start requires repositoryId and mode; optional args are individual arguments passed to the chosen package script for a test subset (never shell syntax); cancel requires runId. Start isolated VPS jobs for public GitHub repositories without a GitHub connection or repo allowlist. Submission IDs are generated by the tool. If a start response is uncertain, list before starting again. Exit code 0 means command success, not individual test-case verification. Jobs continue in the workspace execution card; do not repeatedly poll. Log tails may be truncated.',
  // A top-level object makes the action visible to providers that handle union
  // schemas poorly. The shared discriminated union still validates every action.
  inputSchema: z.object({
    action: z.enum(['list', 'connect', 'start', 'cancel']),
    url: repositorySchema.shape.url.optional(),
    ref: repositorySchema.shape.ref.optional(),
    script: repositorySchema.shape.script.optional(),
    repositoryId: z.string().uuid().optional(),
    mode: z.enum(['inspect', 'test']).optional(),
    runId: z.string().uuid().optional(),
    args: z.array(z.string().max(300)).max(20).optional(),
  }),
  async execute(input, ctx) {
    const auth = ctx.session.auth.current;
    const threadId = auth?.attributes.browserThreadId;
    if (auth?.authenticator !== 'app' || !auth.principalId || typeof threadId !== 'string') return { error: 'Repository testing requires a workspace web chat.' };
    const action = input.action === 'start' ? { ...input, requestId: repositoryRequestId(threadId, ctx.callId) } : input;
    const parsed = repositoryActionSchema.safeParse(action);
    if (!parsed.success) return { error: 'Missing or invalid repository action fields.', fields: parsed.error.issues.map(issue => ({ path: issue.path.join('.'), message: issue.message })) };
    const response = await fetch(`${appOrigin()}/api/internal/repository`, { method: 'POST', headers: internalHeaders(), body: JSON.stringify({ userId: auth.principalId, threadId, input: parsed.data }), signal: ctx.abortSignal });
    if (!response.ok) return { error: 'Repository action failed. Open Repository testing under Testing for details. Do not repeatedly retry.' };
    return repositoryContext(await response.json());
  },
});
