/** Mirrors the scoped dynamic tools in infra/codex-worker/worker.mjs. */
export const vpsToolGuides = [
  {
    id: 'vps-inspect', tool: 'inspect_environment', title: 'Undersök miljön', icon: 'i-lucide-scan-search',
    summary: 'Befintliga repos, beroenden, processer och portar.',
    description: 'Otto undersöker sandlådan innan något ändras. Matchande checkout, installerade beroenden och tjänster kan återanvändas.',
    needs: 'En tilldelad VPS-sandlåda.',
    steps: ['Läs miljön utan att ändra den.', 'Hämta processens logg och exitkod.', 'Utgå från vad som faktiskt finns innan installation eller start.'],
    result: 'Processlogg i Pågående arbete och underlag för nästa kommando.',
    boundary: 'En öppen port bevisar inte att appen fungerar. Misslyckad inspektion betyder inte att miljön är tom.',
    example: 'Undersök befintlig testmiljö och återanvänd det som redan finns.', related: ['vps', 'vps-process'],
  },
  {
    id: 'vps-execute', tool: 'execute', title: 'Kör kommando', icon: 'i-lucide-terminal',
    summary: 'Läs kod, installera, testa och starta tjänster.',
    description: 'Startar ett kommando i den tilldelade isolerade arbetsmiljön. Filer kan läsas via kommandon; kodändringar kräver ett uppdrag som uttryckligen ber om det.',
    needs: 'Genomförd miljöinspektion, kommando och rätt arbetskatalog.',
    steps: ['Välj kommando efter projektets instruktioner och befintliga tillstånd.', 'Starta processen i sandlådan.', 'Läs processresultatet innan en slutsats dras.'],
    result: 'Process-ID, loggar och exitkod i Pågående arbete.',
    boundary: 'Exitkod 0 bevisar bara att kommandot lyckades. Appstart behöver HTTP-kontroll, och funktioner behöver egna tester.',
    example: 'Starta appen med projektets dokumenterade kommando och kontrollera HTTP-svaret.', related: ['vps', 'vps-process', 'vps-environment'],
  },
  {
    id: 'vps-process', tool: 'process', title: 'Läs process', icon: 'i-lucide-scroll-text',
    summary: 'Status, loggutmatning och exitkod.',
    description: 'Läser en process som det aktuella uppdraget har startat. Ger agenten konkret underlag för att bedöma installation, start eller testkommando.',
    needs: 'Ett process-ID som tillhör uppdraget.',
    steps: ['Hämta processens status.', 'Läs standardutmatning och felutmatning.', 'Rapportera verifierade resultat och kvarstående begränsningar.'],
    result: 'Tillgänglig processlogg i Pågående arbete.',
    boundary: 'Loggutmatningen är begränsad i storlek. En körande process är inget färdigt eller godkänt testresultat.',
    example: 'Läs senaste processloggen och förklara vad som faktiskt blev klart.', related: ['vps', 'vps-execute', 'vps-stop'],
  },
  {
    id: 'vps-stop', tool: 'stop_process', title: 'Stoppa process', icon: 'i-lucide-square',
    summary: 'Avbryt en process från det egna uppdraget.',
    description: 'Stoppar en process som Otto har startat inom uppdraget. Verktyget ger inte åtkomst till andra användares processer.',
    needs: 'Ett process-ID som tillhör uppdraget.',
    steps: ['Identifiera rätt process.', 'Begär stopp i sandlådan.', 'Läs returstatus och redovisa eventuella delresultat.'],
    result: 'Processens status och kvarvarande logg.',
    boundary: 'Stopp återställer inte tidigare ändringar och räknas inte som ett slutfört test.',
    example: 'Avbryt testkommandot och sammanfatta de delresultat som finns.', related: ['vps', 'vps-process'],
  },
  {
    id: 'vps-environment', tool: 'report_environment', title: 'Rapportera testmiljö', icon: 'i-lucide-clipboard-check',
    summary: 'Repo, commit, appstart, HTTP och saknad konfiguration.',
    description: 'Rapporterar startkommando, port och saknade variabelnamn. Körmiljön kontrollerar repoidentitet, commit och HTTP-status innan appen bedöms redo.',
    needs: 'Inspekterad miljö, projektkatalog, startkommando och port. Begäran om obligatorisk konfiguration behöver en kopplad startprocess.',
    steps: ['Läs projektets konfiguration och dokumentation.', 'Rapportera den observerade starten och relevanta saknade variabelnamn, aldrig värden.', 'Visa konfigurationsformuläret vid behov; lämna verifierad port till huvudagentens preview.'],
    result: 'Testmiljöns status och vid behov Konfigurera testmiljön i Pågående arbete.',
    boundary: 'HTTP 500 betyder inte testklar. Preview öppnas via huvudagentens verktyg; Iris utför webbläsartesterna.',
    example: 'Kontrollera om appen är testklar och visa vilka inställningar jag behöver fylla i.', related: ['vps', 'browser', 'testing'],
  },
] as const;
