import { defineDynamic, defineInstructions } from 'eve/instructions';
import { canUseCodex, resolveCodexAccess } from '../../infra/codex-worker/access.mjs';

export default defineDynamic({ events: {
  'turn.started': (_event, ctx) => defineInstructions({ markdown: 'Current Otto access policy for this turn: this replaces any older Codex pilot/access instructions retained from this chat. ' + (
    ctx.session.auth.current?.authenticator === 'app' && canUseCodex(ctx.session.auth.current.principalId, resolveCodexAccess(process.env.CODEX_ACCESS_MODE, process.env.CODEX_PILOT_USER_ID))
      ? 'Otto is enabled for this authenticated caller. QA of app or browser behavior belongs to qa_mission with repository surface application, including any necessary startup even when the user did not explicitly ask to start it; that controller delegates preparation to Otto. Do not start its setup separately with codex. Use codex(action: start, task) only for an explicitly requested standalone installation, app start, setup diagnosis or read-only repository architecture map outside an autonomous QA assignment. For a map, use mode repository_map; never install or start an app merely to map it. Include the bounded standalone goal and any observed paths/revisions. Otto operates inside this caller\'s isolated VPS sandbox and inspects it before changes. VPS capacity is shared across users; files, processes, jobs and Vault remain scoped to their owners. Only one Otto task runs at a time. If shared capacity is busy, report that no new job started; never ask this user to inspect another user\'s job or duplicate it through a different executor. Do not duplicate active work with bash, repository or another specialist. After starting a background job, acknowledge it briefly and end your turn immediately so the user can keep chatting. Never poll or wait for it, including with bash. Use codex status only on a later user request to read verified results; a submitted task is not completion. Open preview for a verified running port after completion. Direct browser and repository tools likewise serve explicitly requested one-off operations outside a QA assignment. The open workspace displays completion summaries automatically above the composer and details in Pågående arbete. Registered setup jobs send a background report to this chat. Missing configuration requires the project environment form. For a standalone app start, report verified readiness and its preview; do not append a QA pipeline to this direct setup job. Do not promise automatic retries.'
      : 'Otto is not enabled for new tasks for this caller. Do not select the codex tool automatically. The existing repository and sandbox tools remain available for their supported tasks. Existing owned Otto jobs can still be inspected or cancelled.'),
  }),
} });
