import { defineDynamic, defineInstructions } from 'eve/instructions';
import { canUseCodex, resolveCodexAccess } from '../../infra/codex-worker/access.mjs';

export default defineDynamic({ events: {
  'turn.started': (_event, ctx) => defineInstructions({ markdown: 'Current Otto access policy for this turn: this replaces any older Codex pilot/access instructions retained from this chat. ' + (
    ctx.session.auth.current?.authenticator === 'app' && canUseCodex(ctx.session.auth.current.principalId, resolveCodexAccess(process.env.CODEX_ACCESS_MODE, process.env.CODEX_PILOT_USER_ID))
      ? 'Otto is enabled for this authenticated caller through the codex tool. For repository installation, starting a local application, or diagnosing setup failures, delegate with codex(action: start, task). Include the user goal and any observed paths/revisions. Otto operates inside this caller\'s isolated VPS sandbox and inspects it before changes. VPS capacity is shared across users; files, processes, jobs and Vault remain scoped to their owners. Only one Otto task runs at a time. If shared capacity is busy, report that no new job started; never ask this user to inspect another user\'s job or duplicate it through a different executor. Do not duplicate active work with bash, repository or another specialist. After starting a background job, acknowledge it briefly and end your turn immediately so the user can keep chatting. Never poll or wait for it, including with bash. Use codex status only on a later user request to read verified results; a submitted task is not completion. Open preview for a verified running port after completion. Keep the normal browser tools for browser-only tasks and repository for explicit bounded checks. The open workspace displays completion summaries automatically above the composer and details in Pågående arbete. Registered setup jobs send a background report to this chat. Missing configuration requires the project environment form. After verified HTTP readiness, continue only the originally authorized tests. Do not promise automatic retries.'
      : 'Otto is not enabled for new tasks for this caller. Do not select the codex tool automatically. The existing repository and sandbox tools remain available for their supported tasks. Existing owned Otto jobs can still be inspected or cancelled.'),
  }),
} });
